#!/bin/bash

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(git rev-parse --short HEAD)

if [[ $DOCKER_TAG == *"_latest" ]] ; then
  REDIS_RELEASE="${DOCKER_TAG%_*}"
else
  REDIS_RELEASE="$DOCKER_TAG"
fi

docker build\
  --build-arg BUILD_DATE="$BUILD_DATE"\
  --build-arg VCS_REF="$VCS_REF"\
  --build-arg REDIS_RELEASE="$REDIS_RELEASE"\
  -t "$IMAGE_NAME" .
