# -*- mode: ruby -*-
# vi: set ft=ruby :

# ref, https://app.vagrantup.com/ailispaw/boxes/barge
# A dummy plugin for Barge to set hostname and network correctly at the very first `vagrant up`
module VagrantPlugins
  module GuestLinux
    class Plugin < Vagrant.plugin("2")
      guest_capability("linux", "change_host_name") { Cap::ChangeHostName }
      guest_capability("linux", "configure_networks") { Cap::ConfigureNetworks }
    end
  end
end

Vagrant.configure("2") do |config|
  # config.vm.provider "virtualbox"
  # config.vm.box = "minimum/centos-7-docker"
  # config.vm.box = "centos/7"
  config.vm.define "barge"

  config.vm.box = "ailispaw/barge"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "docker" do |d|
    d.pull_images "java:8u111-jdk"
  end

end


