# -*- mode: ruby -*-
# vi: set ft=ruby :

# Get git configuration from host

begin
  $git_user = `git config --global user.name`.chomp
  $git_email = `git config --global user.email`.chomp
rescue
  puts
  puts "Error running git! Is it installed?"
  puts
  exit
end

if !$git_user || $git_user.empty? || !$git_email || $git_email.empty? then
  puts
  puts "Git not installed or configured."
  puts "Before using this vagrant configuration, please install git and configure it with your name and email address:"
  puts ""
  puts "$ git config --global user.name <your name>"
  puts "$ git config --global user.email <your email>"
  puts
  exit
end

if !File.file? "id_rsa" then
  `ssh-keygen -t rsa -b 4096 -N "" -C #{$git_email} -f id_rsa`
  `cat id_rsa.pub | pbcopy`

  # Add github to ssh known hosts
  File.open("known_hosts", "w") { |file|
    file.puts "github.com,192.30.253.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  }

  puts
  puts "The following SSH key has been generated for Vagrant and has been copied to the clipboard. Please add this key to your GitHub account:"
  puts
  puts File.read "id_rsa.pub"
  puts
  puts "Press ENTER to continue after adding this key to GitHub."
  STDIN.gets
end

def provision(shell, sudo)
  # both shell and suo are lambdas
  # install pre-req packages


end


Vagrant.configure("2") do |config|
  config.vm.box = "jamesthinkbox/ubuntu-16.04-desktop-amd64"
  
  config.vm.provider :virtualbox do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.gui = true
  end
end


