# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision :shell, path: "bootstrap.sh"

  # set memory
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    # v.cpus = 2
  end
  
end