source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in my-second-plugin.gemspec
group :development do
    gem "vagrant", git: "https://github.com/mitchellh/vagrant.git"
end
  
group :plugins do
    gem "my-second-plugin", path: "."
end