#!/usr/bin/env bash

# setup

mkdir /tmp/tmsu/dir
touch /tmp/tmsu/{file1,file2,file3}
tmsu tag --tags=aubergine /tmp/tmsu/dir/{file1,file2}    >/dev/null 2>&1

# test

tmsu untagged --directory /tmp/tmsu/dir                  >>/tmp/tmsu/stdout 2>>/tmp/tmsu/stderr

# verify

diff /tmp/tmsu/stderr - <<EOF
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi

diff /tmp/tmsu/stdout - <<EOF
/tmp/tmsu/dir
EOF
if [[ $? -ne 0 ]]; then
    exit 1
fi
