#/bin/sh

# Query: dockerfiles alpine

snip https://github.com/andreyk0/docker-haskell-platform-alpine
snip https://github.com/tolstoyevsky/mmb
snip https://github.com/BirdBolt/NGINX-uwsgi-Django
snip https://github.com/Starbix/dockerimages
snip https://github.com/bitwalker/alpine-elixir
snip https://github.com/dockette/adminer
snip https://github.com/dweomer/dockerfiles-consul
snip https://github.com/dweomer/dockerfiles-vault
snip https://github.com/dockette/alpine
snip https://github.com/dockette/nodejs
snip https://github.com/JermineHu/docker-opencv
snip https://github.com/burakince/docker-dredd
snip https://github.com/vincentchalamon/docker
snip https://github.com/webdevops/Dockerfile
snip https://github.com/halter73/alpine-investigation
snip https://github.com/dweomer/dockerfiles-serf
snip https://github.com/edv/docker-spotweb
snip https://github.com/nrobinaubertin/dockerfiles
snip https://github.com/kangaechu/docker-alpine-nlp-jp-jupyter
snip https://github.com/pad92/hugo-build
snip https://github.com/kangaechu/docker-alpine-nlp-jp
snip https://github.com/Zenika/alpine-chrome
snip https://github.com/generiklimited/ansible-docker
snip https://github.com/michellabbe/docker-ts3server
snip https://github.com/saitas/alpine-cloud9
snip https://github.com/quchao/nutshells
snip https://github.com/danilofalcao/dockerfiles
snip https://github.com/Zenika/alpine-kotlin
snip https://github.com/syldexiahime/alpine-clang-docker
snip https://github.com/ngchianglin/Docker-Alpine-NginxContentFilter
snip https://github.com/gounthar/alpine-linux-curl
snip https://github.com/AlexMasterov/dockerfiles
snip https://github.com/nreymundo/custom-telegraf-docker-image
snip https://github.com/HariSekhon/Dockerfiles
snip https://github.com/artus/alpine-bigchaindb
snip https://github.com/labulaka521/docker_alpine
snip https://github.com/basistime/netcdf-dockerfiles
snip https://github.com/WinstonH/dockerhub
snip https://github.com/khs1994-docker/php-fpm
snip https://github.com/rvernica/docker-library
snip https://github.com/matsuu/docker-azure-cli
snip https://github.com/stawidy/shadowsocks-libev-docker
snip https://github.com/luisg595/Dockerfile-php7.2-nginx-alpine
snip https://github.com/equanz/golang-alpine-node
snip https://github.com/nmvalera/mythril-alpine
snip https://github.com/vimond/vimond-base-java-8
snip https://github.com/pwittchen/dockerfiles-java
snip https://github.com/royge/python-docker
snip https://github.com/mvertes/docker-alpine-mongo
snip https://github.com/batch9703/dockerfile-alpine-rails
snip https://github.com/ToeiRei/etherpad-docker
snip https://github.com/dockette/ci
snip https://github.com/batch9703/dockerfile-alpine-redis
snip https://github.com/n0b0dyvn/Docker-alpine-php-apache2
snip https://github.com/esycat/docker-upsource
snip https://github.com/arukasio/arukas-alpine
snip https://github.com/Jiri-Kremser/hawkular-services-mini-dockerfiles
snip https://github.com/Horgix/docker-salt-master
snip https://github.com/JohannesEH/yarn-alpine
snip https://github.com/michellabbe/docker-openspeedtest
snip https://github.com/michellabbe/docker-iperf
snip https://github.com/ztyhehe/mongo-alpine
snip https://github.com/raveious/FastRTPS-Alpine-Image
snip https://github.com/codecasts/php-alpine
snip https://github.com/nextmetaphor/dockerized-alpine-gcc
snip https://github.com/RemyJeancolas/dockerfile-optimization
snip https://github.com/cloudposse/fluentd-datadog-logs
snip https://github.com/lebedajaromir/nginx-assignment
snip https://github.com/xcafebabe/gobstoppers
snip https://github.com/stevesbrain/znc-alpine-push
snip https://github.com/DeepInThought/bloodhound-alpine
snip https://github.com/danhigham/alpine-opencv
snip https://github.com/dweomer/dockerfiles-nomad
snip https://github.com/str1k3r/docker
snip https://github.com/ianhattendorf/docker-alpine-git
snip https://github.com/ianhattendorf/docker-alpine-doxygen
snip https://github.com/dweomer/dockerfiles-terraform
snip https://github.com/Riverfount/apache2_alpine_dockerfile
snip https://github.com/nicholasgcoles/pygdal-alpine
snip https://github.com/herrberk/docker-alpine-glibc
snip https://github.com/norrkin/dockerfiles
snip https://github.com/jamesbrink/docker-php
snip https://github.com/Jamesway/docker-php71-cli-dev
snip https://github.com/oildex/docker-aws-cli
snip https://github.com/oildex/docker-jq
snip https://github.com/oildex/docker-ansible-lint
snip https://github.com/oildex/docker-socat
snip https://github.com/Tilkal/docker-node-python-alpine
snip https://github.com/covis/angular-cli
snip https://github.com/symbols-worldwide/docker-minimal-ruby
snip https://github.com/danieldggomes/alpine
snip https://github.com/LoicLemerlus/smashing-alpine
snip https://github.com/blairg/docker-node-sass-alpine
snip https://github.com/unxnn/docker-php
snip https://github.com/Kuangcp/DockerfileList
snip https://github.com/stevelacy/nodejs-native-dockerfile
snip https://github.com/mmospanenko/docker-node-fabric
snip https://github.com/keke-chen/alpine-sbt-vim
snip https://github.com/mec/php-alpine-apache
snip https://github.com/cblunt/alpine-linux-ruby-dockerfile
snip https://github.com/arulrajnet/dockerfiles
snip https://github.com/tloist/docker-alpine-sbt-extras
snip https://github.com/chenjun3092/docker-alpine-jre
snip https://github.com/hazbo/phoenix-docker-alpine
snip https://github.com/lioncui/alpine-tomcat
snip https://github.com/0zores/alpine-wildfly
snip https://github.com/seuf/docker-alpine-wetty
snip https://github.com/dweomer/dockerfiles-openldap
snip https://github.com/Nessex/ats-docker
snip https://github.com/lioncui/alpine-sshd
snip https://github.com/lioncui/alpine-python
snip https://github.com/nicdoye/alpine-rvm-gcc
snip https://github.com/nicdoye/alpine-rvm
snip https://github.com/seuf/zabbix-docker
snip https://github.com/dsys/alpine-node
snip https://github.com/zacksiri/docker-ruby-node
snip https://github.com/marsmensch/docker-alpine-radare2
snip https://github.com/josefcs/docker-alpine-templates
snip https://github.com/DavidWittman/kibana-dockerfile
snip https://github.com/metavige/alpine-nginx
snip https://github.com/leannenorthrop/rpi-alpine-glibc
snip https://github.com/cxhernandez/alpinecuda
snip https://github.com/dweomer/dockerfiles-saslauthd
snip https://github.com/snakeliwei/alpineRuby
snip https://github.com/marcusandre/docker-phpunit
snip https://github.com/GoodGuide/dockerfile-alpine-nodejs
snip https://github.com/prehensile/alpine-python2
snip https://github.com/zyfdegh/dockerfile-2048
snip https://github.com/jonbrouse/alp-deluge
snip https://github.com/develephant/alpine-darkhttpd
snip https://github.com/racker/alpine-py3-web-app-dockerfile
snip https://github.com/gerco/shellinabox-alpine
snip https://github.com/BWITS/tor
snip https://github.com/btnguyen2k/docker-oraclejdk8_jre-alpine
snip https://github.com/nikom/alpine-java-base
snip https://github.com/AntouanK/alpine-iojs
snip https://github.com/idwaker/alpine-mariadb
snip https://github.com/lykhouzov/alpine-nginx
snip https://github.com/lykhouzov/alpine-php
snip https://github.com/infoslack/docker-alpine
snip https://github.com/yumitsu/docker-alpine-sonar
snip https://github.com/Ikke/docker-alpine-redmine
snip https://github.com/picmonkey/alpine-node-onbuild
snip https://github.com/jackMannino/docker-alpine-curl
snip https://github.com/KunalGautam/lamp-alpine
snip https://github.com/TimeFinger/alpine-httpd2-php5
snip https://github.com/wayarmy/alpine-kubectl
snip https://github.com/thesheff17/alpine_dev
snip https://github.com/valer-cara/jmx_exporter
snip https://github.com/scolagreco/docker-apache24
snip https://github.com/archawat/docker-alpine-tika-server
snip https://github.com/anecula/alpine-meetings-registration-tool
snip https://github.com/seuf/riemann-docker
snip https://github.com/egobude/docker
snip https://github.com/jcdarwin/docker-ghost-alpine
snip https://github.com/raghav135/alpine-dnsmasq
snip https://github.com/aseith/ruby-sqlite-sinatra-alpine
snip https://github.com/steffneff/alpine-jdk8
snip https://github.com/boxp/make-alpine
snip https://github.com/eeye/openvpn-client
snip https://github.com/JJTC-Docker/mariadb
snip https://github.com/fledman/alpine_elixir_dockerfiles
snip https://github.com/pschatzmann/docker-websvn
snip https://github.com/rmitsch/docker-alpine-python-nlp
snip https://github.com/seendex/rails-pq
snip https://github.com/top/Dockerfiles
snip https://github.com/nirosys/docker-libboost
snip https://github.com/pteich/docker-bitfan
snip https://github.com/adaliszk/lint-dockerfile-docker
snip https://github.com/ayamshanov/slave-dns
snip https://github.com/FireballDWF/docker-alpine-payara
snip https://github.com/FireballDWF/docker-alpine-payara-mysqljdbc
snip https://github.com/hjr555/rpi-sabnzbd
snip https://github.com/faheemmughal/alpine-nginx-nodejs
snip https://github.com/JohnKDay/contiv-test-container
snip https://github.com/rongfengliang/alpine-timezone
snip https://github.com/Koff/alpine-python3-django-uwsgi-nginx
snip https://github.com/sysboss/docker-nginx-with-confd
snip https://github.com/edv/docker-sickrage
snip https://github.com/edv/docker-couchpotato
snip https://github.com/ksylvan/docker-alpine-node
snip https://github.com/davevs/dockerfiles-alpine
snip https://github.com/pteich/docker-summitdb
snip https://github.com/ljucam/alpine-arm-node
snip https://github.com/shakahl/docker-alpine-nginx-rtmp
snip https://github.com/ryanwalls/ansible-aws-docker
snip https://github.com/pteich/docker-consul-template
snip https://github.com/lishuhao/php-docker
snip https://github.com/mwcz/alpine-nginx
snip https://github.com/acartauchenius/docker-reveal
snip https://github.com/mwcz/alpine-varnish
snip https://github.com/chalcedonyt/docker-php7-alpine-lumen
snip https://github.com/Vanuan/rethinkdb-alpine
snip https://github.com/danny-flores-mojix-com/sbt_docker
snip https://github.com/NaderCHASER/GrADS-Container
snip https://github.com/seuf/alpine-minecraft-docker
snip https://github.com/2vcps/vd_container
snip https://github.com/haines/glibc-alpine
snip https://github.com/haines/jre-alpine
snip https://github.com/isdotcom/alpine
snip https://github.com/witi83/scala-sbt-coursier
snip https://github.com/goodrain-apps/alpine
snip https://github.com/blackcappedchickadee/docker-sfdc-ci-builddev
snip https://github.com/dzirtt/musicBot_alpine
snip https://github.com/parchment-io/dockerfiles-httpie
snip https://github.com/nextmetaphor/dockerized-alpine-gatling
snip https://github.com/nextmetaphor/dockerized-alpine-java
snip https://github.com/starjason/sslibev
snip https://github.com/hiskiwi/docker-symfony-php71-nginx-db-alpine
snip https://github.com/nextmetaphor/dockerized-alpine-angular
snip https://github.com/logingood/telegraf-cisco
snip https://github.com/gibbsoft/docker-alpine-iac
snip https://github.com/Artwishlist/alpine-3.6-ruby-2.4.1
snip https://github.com/nathanshimp/unbound-alpine
snip https://github.com/harindaka/node-docker-project-template
snip https://github.com/slynnda/docker-node
snip https://github.com/ptcmariano/Dockerfile-jenkins-nodejs
snip https://github.com/TakiTake/docker-gradle-alpine
snip https://github.com/dangerfarms/geodrf-alpine
snip https://github.com/zyfdegh/dockerfile-ssserver
snip https://github.com/hmiefert/docker-pi3-go-autorun
snip https://github.com/snowping/humhub.docker
snip https://github.com/auzty/webserv-alpine
snip https://github.com/JJTC-Docker/python
snip https://github.com/firesh/docker-alpine-notify
snip https://github.com/wangxiaoleiAI/docker-alpine
snip https://github.com/atonderski/docker-scipy-alpine
snip https://github.com/docktermj/docker-alpine
snip https://github.com/jinal--shah/docker_build_scripts
snip https://github.com/joaquindlz/docker-docl
snip https://github.com/joney000/Docker-Tomcat-User-Xml
snip https://github.com/TechMaster/alpine_postgis
snip https://github.com/edv/docker-headphones
snip https://github.com/JaviPG/docker-alpine-node
snip https://github.com/abedurftig/dasnervtdoch-sbt-node
snip https://github.com/abedurftig/dasnervtdoch-sbt
snip https://github.com/tabrindle/min-alpine-android-sdk
snip https://github.com/maikyguanaes/alpinium
snip https://github.com/sjug/alpine-minerd
snip https://github.com/boyle-io/alpine-bash
snip https://github.com/LennonRuangjaroon/alpine-java8-jre
snip https://github.com/cnagel85/lightweight-mailcatcher-docker
snip https://github.com/seuf/alpine-ngircd-alpine
snip https://github.com/seuf/alpine-mariadb-docker
snip https://github.com/Adam-Ant/docker-teamspeak3
snip https://github.com/prapdm/php7
snip https://github.com/codingtony/rpi-php
snip https://github.com/scorputty/transmission
snip https://github.com/scorputty/sickrage
snip https://github.com/scorputty/couchpotato
snip https://github.com/rafaelkallis/alpine-node-nginx
snip https://github.com/comodal/alpine-jdk-mono
snip https://github.com/G2Jose/node
snip https://github.com/banaio/golang-docker-alpine-bench
snip https://github.com/Speedy37/docker-teamspeak3
snip https://github.com/comodal/alpine-redis-testing
snip https://github.com/drubb/docker-alpine-base
snip https://github.com/kiview/openjdk-alpine-bash
snip https://github.com/andyet/node
snip https://github.com/mherwig/docker-alpine-java-mongo
snip https://github.com/mrmike/alpine-s3cmd
snip https://github.com/babie/docker-goapp
snip https://github.com/stakater/dockerfile-collectd
snip https://github.com/radhus/alpine-networking-dockerfiles
snip https://github.com/rizo928/alpine-fpm-wordpress
snip https://github.com/thebinary/docker-alpine-flask
snip https://github.com/pschatzmann/docker-jenkins
snip https://github.com/pschatzmann/docker-flume
snip https://github.com/kosecki123/wolf-miner-alpine
snip https://github.com/jayderfranca/docker-alpine-zuul
snip https://github.com/heres/alpine-supervisord
snip https://github.com/adamrbell/alpine-python3
snip https://github.com/JulienBalestra/nginx
snip https://github.com/tloist/docker-alpine-sbt
snip https://github.com/nguse/docker-alpine-apache-php
snip https://github.com/zaradoz/autossh-docker
snip https://github.com/ljnelson/docker-calibre-alpine
snip https://github.com/xslim/Dockerfiles
snip https://github.com/ggicci/docker-shadowsocks
snip https://github.com/lucmichalski/Redis-KV-Alpine-Dockerfile
snip https://github.com/edwinek/alpine-jdk8-maven
snip https://github.com/comodal/alpine-redis
snip https://github.com/comodal/alpine-cloud-sdk
snip https://github.com/comodal/alpine-aws-cli
snip https://github.com/comodal/alpine-gcc-make
snip https://github.com/comodal/alpine-stunnel
snip https://github.com/strayge/alpine-py3-numpy-scipy
snip https://github.com/lgelfan/mariadb-alpine
snip https://github.com/reddyalready/traefik-alpine-docker
snip https://github.com/eengelking/alpine-nginx-phpfpm
snip https://github.com/mrasband/python3.5-alpine-essentials
snip https://github.com/seals55/alpine-more
snip https://github.com/desteves/alpy-adb
snip https://github.com/5003/alpine-edge-dockerfiles
snip https://github.com/vlastv/docker-php
snip https://github.com/splieth/docker-java
snip https://github.com/zackelan/docker-transmission
snip https://github.com/xiangpeng/alpine-ruby_app
snip https://github.com/BEVOLTA/ember-alpine
snip https://github.com/mastermind1981/alpine-zcash
snip https://github.com/elsenorrodrigo/SpliceMachineDockerAlpine
snip https://github.com/jheise/rpi-alpine-golang
snip https://github.com/111h/alpine-passenger-standalone
snip https://github.com/mehemken/docker-flask-base
snip https://github.com/valentin2105/dehydrated-docker
snip https://github.com/lipengyu/docker-azkaban
snip https://github.com/raizv/php56
snip https://github.com/borisaka/dockerfiles
snip https://github.com/lcfumes/docker-alpine-nginx-nodejs
snip https://github.com/hoffoo/alpine
snip https://github.com/sumpfgottheit/alpine-python35-numpy
snip https://github.com/kszucs/mesos-alpine
snip https://github.com/bcrochet/docker-sonarr-alpine
snip https://github.com/seuf/sonerezh
snip https://github.com/marsmensch/docker-alpine-tcpdump
snip https://github.com/sturadnidge/dockerhub-alpine-ci
snip https://github.com/jensskott/alpine-node
snip https://github.com/uretgec/docker-redis-alpine
snip https://github.com/Ninicons/node
snip https://github.com/millerjs2/docker-kanboard
snip https://github.com/millerjs2/docker-htmly
snip https://github.com/felixsanz/docker-mongo
snip https://github.com/zyfdegh/dockerfile-webconsole
snip https://github.com/Adam-Ant/docker-minecraft-amp-ALPINE
snip https://github.com/2infinite/openntpd
snip https://github.com/2infinite/transmission
snip https://github.com/2infinite/bind
snip https://github.com/thezodl/Docker-Kirby-Alpine-PHP-Nginx
snip https://github.com/rastut/redis-alpine
snip https://github.com/rastut/ruby-alpine
snip https://github.com/thezodl/Docker-Alpine-PHP7-Nginx
snip https://github.com/codewinkel/docker-java-webapp
snip https://github.com/kan/docker-perl-carton
snip https://github.com/invrs/elixir-alpine-envconsul
snip https://github.com/XMV-Solutions/DockerOwnCloudClient
snip https://github.com/MotionCTL/alpine-dockerfiles
snip https://github.com/Adam-Ant/docker-nginx-php
snip https://github.com/yellowkingdom/ssh-alpine
snip https://github.com/dliappis/dockeralpinelinux
snip https://github.com/winsento/geoserver-alpine
snip https://github.com/m-housh/zsh
snip https://github.com/appleboy/php-docker
snip https://github.com/thrivesmart/docker-alpine-jenkins-golang
snip https://github.com/nisnaker/webstack
snip https://github.com/pandocker/pandocker-alpine
snip https://github.com/bakkerjean/docker-elasticsearch-2.4.6-alpine
snip https://github.com/otassel/docker-python-talib
snip https://github.com/SevenCode/alpine-openjdk
snip https://github.com/walker-walks/alpine_node-oracledb
snip https://github.com/Nexosis/alpine-xgboost
snip https://github.com/marcinmaruszewski/curl
snip https://github.com/rustamzh/openjdk-coq-alpine
snip https://github.com/scolagreco/alpine-php-fpm
snip https://github.com/khast3x/Offensive-Dockerfiles
snip https://github.com/sedlund/duplicacy-cli-docker
snip https://github.com/fzvgu/mkdocs
snip https://github.com/alfg/docker-nginx-rtmp
snip https://github.com/ondrejmo/Dockerfiles
snip https://github.com/evilguy-inc/alpine-dockerfiles
snip https://github.com/raphamendonca/alpine-java9
snip https://github.com/esycat/docker-jetbrains-hub
snip https://github.com/esycat/docker-youtrack
snip https://github.com/proemergotech/nginx-rtmp-opentracing
snip https://github.com/Jamesway/docker-php71-fpm-xdebug
snip https://github.com/leeyenmomoko/Dockerfile-alpine-nginx-php7
snip https://github.com/praveenweb/python-docker
snip https://github.com/qmu/dockerfiles
snip https://github.com/incognitjoe/docker-alpine-scapy3
snip https://github.com/symball/docker-images
snip https://github.com/shahidhk/go-docker
snip https://github.com/mheindl/alpine-python-nodejs
snip https://github.com/quintype/sbt-alpine
snip https://github.com/dweomer/dockerfiles-hashibase
snip https://github.com/dweomer/dockerfiles-gnupg
snip https://github.com/flightstar/CaddyAlpine
snip https://github.com/ryanmoon/marmalade
snip https://github.com/scolagreco/docker-nginx
snip https://github.com/scolagreco/docker-alpine
snip https://github.com/alfg/docker-ffmpeg
snip https://github.com/fabricetriboix/alpine-runit
snip https://github.com/k0pernikus/httpie-docker-alpine
snip https://github.com/dnephin/alpine-package-mirror
snip https://github.com/korchasa/composer2docker
snip https://github.com/timesking/python36_alpine_ansibleplay
snip https://github.com/nopp/jenkins_alpine
snip https://github.com/olivier-mauras/docker-alpinelinux
snip https://github.com/scolagreco/alpine-openjdk-springboot
snip https://github.com/jmckind/docker-openssl
snip https://github.com/praveenweb/node-docker
snip https://github.com/scolagreco/alpine-openjdk
snip https://github.com/endam/docker-alpine-angular
snip https://github.com/timonweb/docker-cron-swissknife
snip https://github.com/Stanback/alpine-strongswan-vpn
snip https://github.com/maschel/docker-crond
snip https://github.com/john-e/docker-alpine-nginx-php7-mongo
snip https://github.com/cylim/alpine-node
snip https://github.com/lummm/openresty-postgres-docker
snip https://github.com/sspn-thedatacoder/AlpineOpenJDK8
snip https://github.com/joyzoursky/docker-python-chromedriver
snip https://github.com/onthedock/alpine-dnsmasq
snip https://github.com/hiskiwi/docker-symfony-php71-nginx-alpine
snip https://github.com/Wonderfall/dockerfiles
snip https://github.com/phaneendra/dockerfiles
snip https://github.com/nopp/grafana_alpine
snip https://github.com/seuf/alpine-ttrss-docker
snip https://github.com/ncc0706/alpine-dockerfiles
snip https://github.com/IoTPlay/docker_py_paradox
snip https://github.com/stakater/dockerfile-kops-ansible
snip https://github.com/khs-projects/khs-docker-maven-git
snip https://github.com/scorputty/sabnzbd
snip https://github.com/ljv5555/khs-docker-maven-git
snip https://github.com/kabili207/docker-piaware
snip https://github.com/HE-Arc/demo-laravel-application
snip https://github.com/BarnabyShearer/docker-shinken
snip https://github.com/rohitggarg/docker-ruby-dev
snip https://github.com/ppdeassis/docker-node-nginx-alpine
snip https://github.com/dweomer/dockerfiles-awscfn
snip https://github.com/dweomer/dockerfiles-awscli
snip https://github.com/Bulbahsan/docker-alpine-transmission-ui
snip https://github.com/chuyqa/plowdown
snip https://github.com/songyunlu/container-network-tools
snip https://github.com/samar-agrawal/alpine-sanic-aiomysql
snip https://github.com/PixiBixi/dockerfiles
snip https://github.com/dweomer/dockerfiles-nginx-auth-ldap
snip https://github.com/flachglasschweiz/docker-alpine-gitftp
snip https://github.com/goodrain-apps/docker-alpine-nginx
snip https://github.com/angryquiz/alpine-openjdk
snip https://github.com/byronschaller/awscli-dockerfile
snip https://github.com/seancheung/elstack
snip https://github.com/andreburgaud/docker-coconut
snip https://github.com/timotto/java-node-dockerfile
snip https://github.com/mario21ic/alpine-terraform-packer-ansible-awscli
snip https://github.com/seraphimalia/docker-openjdk8-alpine-plus-fonts
snip https://github.com/stakater/dockerfile-java
snip https://github.com/michellabbe/docker-speedtest-mini
snip https://github.com/me1ram/nginx-alpine
snip https://github.com/eucledian/FreeRadiusDocker
snip https://github.com/pepijnblom/docker-alpine-proxysql
snip https://github.com/astaldo10/alpine-kafka-elasticsearch
snip https://github.com/geils/tomcat8-jdk8-alpine
snip https://github.com/yuyongpeng/docker-php
snip https://github.com/xataz/dockerfiles
snip https://github.com/myandpr/dockerfile-alpine-filebeat
